### PR TITLE
corrected grammar in first notes, discord-like embeds for discord servers

### PR DESCRIPTION
**Pull request by xstyyy**
I used https://invidget.switchblade.xyz/ (https://github.com/SwitchbladeBot/invidget) for the discord-like server embeds

### CODE REVIEW

**Comment by xstyyy** [comment]
I just realised that maybe the embeds weren't the best idea but it's whatever

**Comment by iAndyHD3** [comment]
if on clicking the embed it opened the invite it would be fine

**Comment by xstyyy** [comment]
> if on clicking the embed it opened the invite it would be fine

keeping it as a list is probably better, because the embed just opens as an image, and then you can press it to join the server

**Comment by iAndyHD3** [comment]
i will see if i can make them work as i said, thanks for suggestion. i didnt know about this invite embed

**Pull request closed without merging**
